name: era_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  gap: ^3.0.1
  go_router: ^13.1.0
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  easy_localization: ^3.0.4
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0

flutter:
   uses-material-design: true
   assets:
      - assets/
      - assets/icons/
      - assets/icons/svg/

   fonts:
    - family: sf_pro_display
      fonts:
        - asset: fonts/sf_pro_display/SFPRODISPLAYREGULAR.OTF
